### ISSUE TITLE
getVertexSetSize()

### ISSUE THREAD

**Issue by jrmh96** [GraphIt-DSL/graphit#144]
I noticed within tc.gt, if you call
`src_nghs.getVertexSetSize()`
this will always be 0, even though the true size is `edges.getOutDegree(src)`, I noticed similar behavior on a file I'm working on right now. Is the size of `src_nghs` actually 0, or is it an issue w. getVertexSetSize()?

**Comment by yunmingzhang17** [comment]
Hi Jeremy, 

Thanks for the note! 
@tugsbayasgalan, can you look into this issue a bit?

**Comment by tugsbayasgalan** [comment]
Hi Jeremy,

The issue should have been fixed. Could you pull from master and check? 

Best,
Tugsuu

**Comment by jrmh96** [comment]
Hi Tugsuu, 
Yes it looks consistent now! Closing this issue.

Best, Jeremy
