### ISSUE TITLE
The ICPC link seems to be broken

### ISSUE THREAD

**Issue by Krtoeezi** [GraphIt-DSL/graphit#146]
Hi!
  I am a student who is learning to use graphit. I noticed that the link to ICPC, the compiler that supports Cilk and OpenMP, had been changed to a download link to OneAPI. And the download link of ICPC seems to be hard to find. Could you send me a copy if it is convenient for you? Also, does Graphit support OneAPI? and is it possible to install Cilk and OpenMP separately?

**Comment by yunmingzhang17** [comment]
Hi, 

Thanks for the note. I guess we haven't tried to build GrapIt with OneAPI yet. Maybe it will be easier if you just use the CILK  or OpenMP that comes with gcc? I think GCC has support for CILK before it is dropped in GCC8. We have been using the gcc version lately as well.

**Comment by Krtoeezi** [comment]
Thank you for your reply. I will try it later.
best wishes!
