### ISSUE TITLE
test_with_schedules.py test failed

### ISSUE THREAD

**Issue by nicelhc13** [GraphIt-DSL/graphit#76]
Hello,
I am trying to install Graphit but I got several errors during 'test_with_schedules.py' tests.
From starting the error at "graphitc.py", line 76, "CalledProcessError", a tons of errors is printed out.
I guess it would be invoked due to specifying paths.
Could you help me to solve the issue?

Thank you,

**Comment by yunmingzhang17** [comment]
Hi, 

Sorry to hear that. We couldn't figure out the reason based on the line number in graphitc.py. Could you provide us with a bit more information? 

(1) Could you show us the full error message? (if it is too long, you can email it to me at yunming@mit.edu)
(2) Could you tell me the version of g++ and Python that you are using?  
(3) Could you show me the commands that you have executed so far (the exact reference step is in the README file)? For example, what is the name of the build directory you created and other steps you have done? 

Thanks

**Comment by nicelhc13** [comment]
Sure, I will email to you! Thank you.
