### ISSUE TITLE
More algorithms

### ISSUE THREAD

**Issue by chenyi95** [GraphIt-DSL/graphit#86]
Very nice project as well as your paper.

I noticed the proposed algorithms are with number variables (int, float, double, vector<..>).
I was wondering if other variables like string could be added.

For example, to implement label propagation algorithm,
we may want:
`const label: vector{Vertex}(string)`

Is that possible and how to initialized the label variable?
Any comments would be appreciated. Thanks.

**Comment by yunmingzhang17** [comment]
Hi Chenyi,

Thanks for your interest in the project!
It should be possible, but I haven't tried to implement a label propagation with strings yet. 
Do you have a specific algorithm in mind? or a C++ implementation somewhere so that we can give you more advice on how to implement it, or try it out ourselves? 

Thanks

**Comment by chenyi95** [comment]
Hi Yunming,  I quickly did some searching on github, and found this one looks similar https://github.com/meysam81/node-importance-LPA

Anyway, we can encode the string labels to numbers and use integer labels as that project does.
But sometimes string labels make the results more readable.
http://ai.googleblog.com/2016/10/graph-powered-machine-learning-at-google.html
https://ai.google/research/pubs/pub41144

LP is like a mix of pagerank and connected component, passing the weight of label to activate the neighbors. Some traditional methods use '?' or ID for some unlabeled nodes.

**Comment by yunmingzhang17** [comment]
HI Chenyi, 

Thanks for the note. We should be able to implement a more generic label propagation algorithm. We do use label propagation currently for connected components. We might need to add support for more operations on strings. 

I will keep you updated. 

Thanks

**Comment by chenyi95** [comment]
Thanks

**Comment by yunmingzhang17** [comment]
Let us know if you run into any issues when testing GraphIt? We would be happy to take a look at it.
